# uvod

In [2]:
pip install numpy

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/c5/9e/2d6d9d8f0ec910539ee721f86f23489a0eedb25bd51f4268ae0899f6a3ab/numpy-1.26.1-cp311-cp311-macosx_10_9_x86_64.whl.metadata
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 995.1 kB/s eta 0:00:00 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.6/20.6 MB 8.4 MB/s eta 0:00:0000:0100:01m

[notice] A new release of pip is available: 23.2.1 -> 23.3
[notice] To update, run: /usr/local/Cellar/jupyterlab/4.0.7/libexec/bin/python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np
a = np.array(5)
a

array(5)

In [5]:
print(a)

5


In [6]:
#komentar 

# tipovi podataka

In [7]:
i = 5 # interger
f = 5.0 #float
s = '5' #string, input se uvek ucitava kao string
true = True #boolean = true i false vrednosti
l = [5] #lista - neuredjena
#array - uredjenija lista, moze bolje da se manipulise i treba da ima podatke istog tipa

***

In [8]:
#sam interpretira tip podataka
print(type(i))
print(type(f))
print(type(s))
print(type(true))
print(type(l))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>
<class 'list'>


***

In [9]:
I = float(i)
#menjanje tipa promenljive
print(I)
print(type(I))

5.0
<class 'float'>


In [18]:
l2 = ['broj', 5, 6.0, [5,6,7]]
print(l2)
a=444
b = 333
#dodavanje podataka u listu
l2.append(a)
print(l2)
l2.append(b)
l2

['broj', 5, 6.0, [5, 6, 7]]
['broj', 5, 6.0, [5, 6, 7], 444]


['broj', 5, 6.0, [5, 6, 7], 444, 333]

In [19]:
import numpy as np
a = np.array(5)
type(a)

numpy.ndarray

***
#generisanje nizova brojeva u odredjenom intervalu

In [30]:
#arrange - zadajemo pocetnu, zavrsnu vrednost i korak
print(np.arange(1,100,10))
#linspace - kao u matlabu -zadaje se broj ekvidistantnih tacaka(?) od pocetne i krajnje vrednosti
print(np.linspace(0,100,11))

[ 1 11 21 31 41 51 61 71 81 91]
[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [20]:
print(l * 5)
print(a * 5)

[5, 5, 5, 5, 5]
25


***
generisanje nizova jedinica i nula

In [33]:
print(np.ones_like(np.linspace(1,100,10)))
print(np.zeros_like(np.linspace(1,100,10)))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


***
operacije sa matricama

In [34]:
#razlika izmedju svakog clana
np.diff(np.ones_like(np.linspace(1,100,10)))

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

***

# paketi

In [41]:
pip install --upgrade pip

  Obtaining dependency information for pip from https://files.pythonhosted.org/packages/e0/63/b428aaca15fcd98c39b07ca7149e24bc14205ad0f1c80ba2b01835aedde1/pip-23.3-py3-none-any.whl.metadata
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 11.1 MB/s eta 0:00:0000:010:01
  Attempting uninstall: pip
    Found existing installation: pip 23.2.1
    Not uninstalling pip at /usr/local/lib/python3.11/site-packages, outside environment /usr/local/Cellar/jupyterlab/4.0.7/libexec
    Can't uninstall 'pip'. No files were found to uninstall.
Note: you may need to restart the kernel to use updated packages.


In [15]:
pip install matplotlib

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 152.4/152.4 kB 2.0 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 13.2 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 248.6/248.6 kB 8.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 14.7 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.2/68.2 kB 2.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 17.0 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.1/103.1 kB 3.4 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [37]:
pip install astropy

  Obtaining dependency information for astropy from https://files.pythonhosted.org/packages/3c/db/34a29bc5d0eb2e691e2974632502646d338449f455355cd430e48a21667c/astropy-5.3.4-cp311-cp311-macosx_10_9_x86_64.whl.metadata
  Obtaining dependency information for pyerfa>=2.0 from https://files.pythonhosted.org/packages/45/f6/37c904d9e8d33199a670bf8718204627f2207a49a64779964f735bdd674f/pyerfa-2.0.1.1-cp39-abi3-macosx_10_9_x86_64.whl.metadata
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.1/7.1 MB 8.1 MB/s eta 0:00:0000:0100:01m
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 342.9/342.9 kB 7.9 MB/s eta 0:00:00:00:01

[notice] A new release of pip is available: 23.2.1 -> 23.3
[notice] To update, run: /usr/local/Cellar/jupyterlab/4.0.7/libexec/bin/python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [38]:
pip install ephem

  Obtaining dependency information for ephem from https://files.pythonhosted.org/packages/eb/a8/dc9e99453ae6c959e810f4329ac3d66f8a9f447911928cca88fd2ca1c3c9/ephem-4.1.5-cp311-cp311-macosx_10_9_x86_64.whl.metadata
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 8.3 MB/s eta 0:00:00:00:0100:01

[notice] A new release of pip is available: 23.2.1 -> 23.3
[notice] To update, run: /usr/local/Cellar/jupyterlab/4.0.7/libexec/bin/python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


*****

In [16]:
import numpy as np
import matplotlib.pyplot as plt

import astropy as ap
import ephem as ep

# petlje

for petlja

In [4]:
for i in range(5):
    j = i + 1
print(j)

5


In [6]:
a = [3,7,4,5,8]
#printuje i=ti element iz niza a
for i in a:
    print(i)

3
7
4
5
8


In [12]:
N = [3,7,6,4,5]
for i,n in enumerate(N):
    print(i ,":", n)

0 : 3
1 : 7
2 : 6
3 : 4
4 : 5


In [14]:
for i in range(len(N)):
    print (i)
    print(N[i])

0
3
1
7
2
6
3
4
4
5


while petlja